apiVersion: v1

kind: PersistentVolume

metadata:

  name: pv-volume

  labels:

    type: local

spec:

  storageClassName: manual

  capacity:

    storage: 50Gi

  accessModes:

    - ReadWriteOnce

  hostPath:

    path: "/home/ubuntu/pv-volume"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi

